### ISSUE TITLE
20220418：一天内多次上传只会取最大值

### ISSUE THREAD

**Issue by DDXDaniel** [PkuRH/PKURunningHelper#11]
多次上传跑步记录，比如第一次3km，第二次5km，第三次2km，2km，8km。PKURunner软件显示5次条目都成功上传，但是总里程只显示尝试一次，里程为8km，如图
![WechatIMG238](https://user-images.githubusercontent.com/57580327/163782422-94298df4-0b5d-4308-986e-6027a30e55ea.jpeg)

**Comment by PkuRH** [comment]
https://mp.weixin.qq.com/s/kNXrLBic4QrWW7VA1kYB1g
