### ISSUE TITLE
今天发布了新版runner，不知道abstract有没有更新

### ISSUE THREAD

**Issue by Unlinked7242** [PkuRH/PKURunningHelper#14]

**Comment by zhbzhbzhbz** [comment]
> _No description provided._

我们上学期在期末成绩出来后，已经把所有"大量"使用过"这个"软件的学号（我一条条确认的，怕错杀），提交给体教部的负责老师了，建议三思
我非常希望我可以把有限的时间投入到为大家改善软件使用体验上，而不是放在helper上，我个人为了应对helper额外花了几十小时的无偿时间，并且我个人目前在从事Android安全的公司工作，所以你懂的
无论你是否觉得没必要跑步，我需要保障其他真正跑步了的同学的公平，毕竟在体育课里是算分的
