### ISSUE TITLE
2022.03.13更新后 abstract失效了

### ISSUE THREAD

**Issue by moulai** [PkuRH/PKURunningHelper#6]
PKU Runner于2022.03.13更新了新版本，原来的abstract失效了，应该是又换了结尾的密钥。
请问如何获取新的abstract呢？我尝试反编译了一下新版PKU Runner，没有找到。

**Comment by 82379** [comment]
为什么更新后还是 Incorrect Message Abstract 啊! 难道现在有多种结尾密钥吗?

**Comment by PkuRH** [comment]
> 为什么更新后还是 Incorrect Message Abstract 啊! 难道现在有多种结尾密钥吗?

Android 1.22.0313版本的abstract算法应该和目前代码一致，可以抓包验证一下。

但服务器可能将其他信息不正确的返回信息也设为了 Incorrect Message Abstract，欢迎PR修复ヾ(≧▽≦*)o

**Comment by rmbugs** [comment]
更新之后还是Incorrect Message Abstract

**Comment by ChrisKFZHao** [comment]
截至2022年4月3日，仍然显示'Incorrect Message Abstract'与PKURunner.error.PKURunnerSuccessStateError: resp.json error

**Comment by y553546436** [comment]
现在显示登录成功，但是无法上传record，会抛出如下error
`PKURunner.error.PKURunnerNotVerifiedError: record is not verified, check your running params setting.`

**Comment by rmbugs** [comment]
现在是可以上传上去记录，但是都是0.01km，不合格。但是点进去看的话是有记录圈数的，会不会是生成总里程数据的地方出问题了

**Comment by PkuRH** [comment]
> 现在是可以上传上去记录，但是都是0.01km，不合格。但是点进去看的话是有记录圈数的，会不会是生成总里程数据的地方出问题了

那可能是 distance 单位不一样？
乘个 1000 试试🤔

**Comment by rmbugs** [comment]
> 

是在client.py里面改吗？
因为上传上去的记录里面圈数是正常的

**Comment by ChrisKFZHao** [comment]
请问是修改client.py里第276行的distance数据么

**Comment by rmbugs** [comment]
> 请问是修改client.py里第276行的distance数据么

应该是269行
